[project]
dependencies = [
    "filelock==3.14.0",
    "requests"
]


requires-python = ">=3.10"

[project.optional-dependencies]
extras = [
    "pycowsay==0.0.0.1",
]

[build-system]
requires = ["pdm-backend", "pdm-build-locked==0.2.0"]

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=6.0.0",
]
